apiVersion: batch/v1
kind: Job
metadata:
  name: loadgen-go-diskio
  labels:
    app: loadgen
    target: go-diskio
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: loadgen
        target: go-diskio
    spec:
      restartPolicy: Never
      imagePullSecrets:
        - name: sk-quay
      containers:
        - name: loadgen
          image: <image_registry>/mbsaiaditya/loadgen:v1
          env:
            - name: TARGET_URL
              value: "http://go-diskio.test-iam-mbsa.svc.cluster.local:8080/diskio?records=1000&workers=1"
            - name: CONCURRENCY_LEVELS
              value: "50, 60, 70, 80, 90, 100"
            - name: DURATION_SEC
              value: "10"
            - name: LABEL
              value: "go-diskio"
          resources:
            requests: { cpu: "250m", memory: "256Mi" }
            limits: { cpu: "1", memory: "512Mi" }
