server:
  port: 8080

spring:
  application:
    name: java-compute
  threads:
    virtual:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus,metrics
  endpoint:
    health:
      show-details: never
  metrics:
    tags:
      application: java-compute

logging:
  level:
    root: INFO
